server:
  path: 8081
  servlet:
    context-path: /look/es

spring:
  es:
    #Es地址
    hostName: 42.192.11.203
    #Es端口号
    transport: 9300
    #配置es的集群名称，默认是elasticsearch，es会自动发现在同一网段下的es，如果在同一网段下有多个集群，就可以用这个属性来区分不同的集群
    cluster:
      name: elasticsearch


